baseURL: 'https://more.haydengreener.com'
title: Note Repository
paginate: 5
theme: PaperMod
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
#googleAnalytics: UA-123-45
pygmentsUseClasses: true
minify:
  disableXML: true
  minifyOutput: true
params:
  title: Note Repository
  description: Note Repository description
  keywords:
    - ""
  author: ""
  images:
    - '<link or path of image for opengraph, twitter-cards>'
  DateFormat: 'January 2, 2006'
  defaultTheme: dark
  disableThemeToggle: false
  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: false
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  editPost:
    URL: "https://github.com/plateau12/more.personal/tree/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link
  assets:
    favicon: "<link / abs url>"
    favicon16x16: <link / abs url>
    favicon32x32: <link / abs url>
    apple_touch_icon: <link / abs url>
    safari_pinned_tab: <link / abs url>
  label:
    text: Home
    icon: /apple-touch-icon.png
    iconHeight: 35
  profileMode:
    enabled: true
    title: 🪴 Note Repository
    subtitle: Ping. PONG
    imageUrl: ""
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Written Posts
        url: posts
      - name: Youtube
        url: https://www.youtube.com/@ItsLightMind
      - name: Twitter
        url: https://twitter.com/ItsLightMind
  homeInfoParams:
    Title: "My Notes \U0001F335"
    Content: Pong
  analytics:
    google:
      SiteVerificationTag: XYZabc
    bing:
      SiteVerificationTag: XYZabc
    yandex:
      SiteVerificationTag: XYZabc
  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys:
      - title
      - permalink
      - summary
      - content
menu:
  main:
    - identifier: search
      name: search
      url: /search
      weight: 20
    - identifier: portfolio
      name: portfolio
      url: 'https://haydengreener.com'
      weight: 30
markup:
  highlight:
    noClasses: false
